### ISSUE TITLE
Adding Adspanel to home page (guest access) and directory sidebars

### ISSUE THREAD

**Issue by muriukimk** [WebCrew/humhub-adspanel#1]
I would like to add the adspanel ads to the homepage (guest access) and the directory page sidebars. I am not a very good coder and would appreciate it if you point me in the right direction

**Comment by muriukimk** [comment]
i have managed to place the adspanels on the directory pages. Im still not able to make them viewable by users who are not logged in.

**Comment by WebCrew** [comment]
Sorry, I have also no idea how to show it to guests.
