### ISSUE TITLE
ReflectionException Error

### ISSUE THREAD

**Issue by gigabytedevelopers** [WebCrew/humhub-adspanel#2]
After activating this module on version 1.1, I get a ReflectionException Error saying that Class humhub\modules\adspanel\Module does not exist

**Comment by WebCrew** [comment]
Thank You for reporting the issue. I use my Adspanel module with latest HumHUb (1.1) and it is working well. 
I have no idea about the ReflectionException Error, but I will give it a closer look. Do You also have a error log message about that issue in your HumHub admin backend?

I tested a lot, but I cant find any bug or error. Can You use the Module and only a error message shows up, or does it not install? It would be nice to get a bit more information.

I`m sadly not a pro with HumHub and PHP programming.
