### ISSUE TITLE
Disable AdBlocker Message

### ISSUE THREAD

**Issue by Felli** [WebCrew/humhub-adspanel#3]
You should think about adding a message asking about disabling adblocker into the module, other than this looks good. :+1:

**Comment by WebCrew** [comment]
yeah but how? The idea is good, but I have no idea how I should do it, I think there is a little JavaScript snippet needed and I`m only a beginner with JS Feli.

**Comment by Felli** [comment]
Try [BlockAdBlock](https://github.com/sitexw/BlockAdBlock)?

**Comment by WebCrew** [comment]
thx for the info Feli. I think I`ll integrate only a simple note. The detect ad blocker script is more code as my whole module lol but it is a good idea and I will think about it.
